# Site settings
title: Stefan Bischof - semantic web researcher
email: stefan@stefanbischof.at
description: > # this means to ignore newlines until "baseurl:"
  Hi! I am a research scientist at Siemens AG Österreich and a PhD student with the Technical University of Vienna.
  Semantic Web technologies are useful tools, not only for academia or for fun but also for enterprises. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.stefanbischof.at" # the base hostname & protocol for your site
twitter_username: stefanbischof
github_username:  stefanbischof
author: 
  twitter: stefanbischof
social:
  name: Stefan Bischof
  links:
    - http://twittern.com/stefanbischof
    - http://github.com/stefanbischof
webmaster_verifications:

# Build settings
markdown: kramdown

gems:
#  - 'jekyll/scholar'
#  - jekyll-assets
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-typogrify


include: ['.htaccess']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Stefan Bischof"

collection:
- publications

sass:
    style: compressed
